### ISSUE TITLE
android build issue

### ISSUE THREAD

**Issue by topdeveloper0017** [AgoraIO/React-Native-SDK#11] opened 2018-10-21 23:36 UTC
AgoraModule.java:620: error: method does not override or implement a method from a supertype
            @Override
AgoraModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Please help me with this issue,

**Comment by PRWrl** [comment] 2018-10-22 08:33
Duplicate of #12

**Comment by PRWrl** [comment] 2018-10-22 08:33
Duplicate of #12

**Closed by PRWrl** 2018-10-22 08:33 UTC
